#!/bin/sh

for source in .bundle .gemrc .gitconfig .hushlogin .powconfig .vim .vimrc .zshrc; do
  target=~/`basename $source`
  source=~/.dotfiles/$source

  rm -rf $target
  ln -s $source $target
done

# Setup the subl command
echo "Adding subl command"

sudo ln -s "/Applications/Sublime Text 2.app/Contents/SharedSupport/bin/subl" /bin/subl

touch ~/.z
