#!/bin/sh

for source in .bundle .gemrc .gitconfig .hushlogin .powconfig .vim .vimrc .zshrc .aliases; do
  target=~/`basename $source`
  source=~/Projects/dotfiles/dotfiles/$source

  rm -rf $target
  ln -s $source $target
done
